#pragma once

enum CONTROLLER_DEFINES {

	SDL_CONTROLLER_A,
	SDL_CONTROLLER_B,
	SDL_CONTROLLER_X,
	SDL_CONTROLLER_Y,
	SDL_CONTROLLER_SHOULDER_LEFT,
	SDL_CONTROLLER_SHOULDER_RIGHT,
	SDL_CONTROLLER_SELECT,
	SDL_CONTROLLER_START,
	SDL_CONTROLLER_STICKER_LEFT,
	SDL_CONTROLLER_STICKER_RIGHT,
	SDL_CONTROLLER_DUP,
	SDL_CONTROLLER_DRIGHT,
	SDL_CONTROLLER_DDOWN,
	SDL_CONTROLLER_DLEFT

};
