#pragma once

enum ERROR {

	ERROR_SDL_INIT_VIDEO = 2,
	ERROR_SDL_INIT_AUDIO,
	ERROR_SDL_INIT_JOYSTICK,
	ERROR_SDL_INIT_HAPTIC,
	ERROR_SDL_WINDOW_FAILED_TO_LOAD,
	ERROR_SDL_JOYSTICK_LOAD,
	ERROR_SDL_AUDIO_WAV_LOAD,
	ERROR_SDL_TEXTURE_LOAD,
	ERROR_ARENA_LOAD_FILE,
	ERROR_ARENA_PARSE_JSON

};
